//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Balance.Service.ServiceReference_RemoteRealtimeData {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfDecimal", Namespace="http://tempuri.org/", ItemName="decimal")]
    [System.SerializableAttribute()]
    public class ArrayOfDecimal : System.Collections.Generic.List<decimal> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfBoolean", Namespace="http://tempuri.org/", ItemName="boolean")]
    [System.SerializableAttribute()]
    public class ArrayOfBoolean : System.Collections.Generic.List<bool> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DigitalDataGroup_Serialization", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DigitalDataGroup_Serialization : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganizationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Balance.Service.ServiceReference_RemoteRealtimeData.DigitalDataItem_Serialization[] DataSetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string OrganizationId {
            get {
                return this.OrganizationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizationIdField, value) != true)) {
                    this.OrganizationIdField = value;
                    this.RaisePropertyChanged("OrganizationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Balance.Service.ServiceReference_RemoteRealtimeData.DigitalDataItem_Serialization[] DataSet {
            get {
                return this.DataSetField;
            }
            set {
                if ((object.ReferenceEquals(this.DataSetField, value) != true)) {
                    this.DataSetField = value;
                    this.RaisePropertyChanged("DataSet");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DigitalDataItem_Serialization", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DigitalDataItem_Serialization : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        private bool ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnalogDataGroup_Serialization", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AnalogDataGroup_Serialization : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganizationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Balance.Service.ServiceReference_RemoteRealtimeData.AnalogDataItem_Serialization[] DataSetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string OrganizationId {
            get {
                return this.OrganizationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizationIdField, value) != true)) {
                    this.OrganizationIdField = value;
                    this.RaisePropertyChanged("OrganizationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Balance.Service.ServiceReference_RemoteRealtimeData.AnalogDataItem_Serialization[] DataSet {
            get {
                return this.DataSetField;
            }
            set {
                if ((object.ReferenceEquals(this.DataSetField, value) != true)) {
                    this.DataSetField = value;
                    this.RaisePropertyChanged("DataSet");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnalogDataItem_Serialization", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AnalogDataItem_Serialization : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        private decimal ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjectDataGroup_Serialization", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ObjectDataGroup_Serialization : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganizationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Balance.Service.ServiceReference_RemoteRealtimeData.ObjectDataItem_Serialization[] DataSetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string OrganizationId {
            get {
                return this.OrganizationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizationIdField, value) != true)) {
                    this.OrganizationIdField = value;
                    this.RaisePropertyChanged("OrganizationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Balance.Service.ServiceReference_RemoteRealtimeData.ObjectDataItem_Serialization[] DataSet {
            get {
                return this.DataSetField;
            }
            set {
                if ((object.ReferenceEquals(this.DataSetField, value) != true)) {
                    this.DataSetField = value;
                    this.RaisePropertyChanged("DataSet");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjectDataItem_Serialization", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Balance.Service.ServiceReference_RemoteRealtimeData.ArrayOfString))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Balance.Service.ServiceReference_RemoteRealtimeData.ArrayOfDecimal))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Balance.Service.ServiceReference_RemoteRealtimeData.ArrayOfBoolean))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Balance.Service.ServiceReference_RemoteRealtimeData.DigitalDataGroup_Serialization))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Balance.Service.ServiceReference_RemoteRealtimeData.DigitalDataItem_Serialization[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Balance.Service.ServiceReference_RemoteRealtimeData.DigitalDataItem_Serialization))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Balance.Service.ServiceReference_RemoteRealtimeData.AnalogDataGroup_Serialization))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Balance.Service.ServiceReference_RemoteRealtimeData.AnalogDataItem_Serialization[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Balance.Service.ServiceReference_RemoteRealtimeData.AnalogDataItem_Serialization))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Balance.Service.ServiceReference_RemoteRealtimeData.ObjectDataGroup_Serialization))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Balance.Service.ServiceReference_RemoteRealtimeData.ObjectDataItem_Serialization[]))]
    public partial class ObjectDataItem_Serialization : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public object Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference_RemoteRealtimeData.RealTimeDataSoap")]
    public interface RealTimeDataSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Balance.Service.ServiceReference_RemoteRealtimeData.HelloWorldResponse HelloWorld(Balance.Service.ServiceReference_RemoteRealtimeData.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 myOrganizationId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetAnalogData", ReplyAction="*")]
        Balance.Service.ServiceReference_RemoteRealtimeData.SetAnalogDataResponse SetAnalogData(Balance.Service.ServiceReference_RemoteRealtimeData.SetAnalogDataRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 myOrganizationId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetAnalogDataCompress", ReplyAction="*")]
        Balance.Service.ServiceReference_RemoteRealtimeData.SetAnalogDataCompressResponse SetAnalogDataCompress(Balance.Service.ServiceReference_RemoteRealtimeData.SetAnalogDataCompressRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 myOrganizationId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetDigitalData", ReplyAction="*")]
        Balance.Service.ServiceReference_RemoteRealtimeData.SetDigitalDataResponse SetDigitalData(Balance.Service.ServiceReference_RemoteRealtimeData.SetDigitalDataRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 myOrganizationId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetDigitalDataCompress", ReplyAction="*")]
        Balance.Service.ServiceReference_RemoteRealtimeData.SetDigitalDataCompressResponse SetDigitalDataCompress(Balance.Service.ServiceReference_RemoteRealtimeData.SetDigitalDataCompressRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 myOrganizationId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDigitalDataA", ReplyAction="*")]
        Balance.Service.ServiceReference_RemoteRealtimeData.GetDigitalDataAResponse GetDigitalDataA(Balance.Service.ServiceReference_RemoteRealtimeData.GetDigitalDataARequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 myOrganizationId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAnalogDataA", ReplyAction="*")]
        Balance.Service.ServiceReference_RemoteRealtimeData.GetAnalogDataAResponse GetAnalogDataA(Balance.Service.ServiceReference_RemoteRealtimeData.GetAnalogDataARequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 myOrganizationId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetObjectDataA", ReplyAction="*")]
        Balance.Service.ServiceReference_RemoteRealtimeData.GetObjectDataAResponse GetObjectDataA(Balance.Service.ServiceReference_RemoteRealtimeData.GetObjectDataARequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 myOrganizationId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDigitalDataS", ReplyAction="*")]
        Balance.Service.ServiceReference_RemoteRealtimeData.GetDigitalDataSResponse GetDigitalDataS(Balance.Service.ServiceReference_RemoteRealtimeData.GetDigitalDataSRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 myOrganizationId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAnalogDataS", ReplyAction="*")]
        Balance.Service.ServiceReference_RemoteRealtimeData.GetAnalogDataSResponse GetAnalogDataS(Balance.Service.ServiceReference_RemoteRealtimeData.GetAnalogDataSRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Balance.Service.ServiceReference_RemoteRealtimeData.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Balance.Service.ServiceReference_RemoteRealtimeData.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Balance.Service.ServiceReference_RemoteRealtimeData.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Balance.Service.ServiceReference_RemoteRealtimeData.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetAnalogDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetAnalogData", Namespace="http://tempuri.org/", Order=0)]
        public Balance.Service.ServiceReference_RemoteRealtimeData.SetAnalogDataRequestBody Body;
        
        public SetAnalogDataRequest() {
        }
        
        public SetAnalogDataRequest(Balance.Service.ServiceReference_RemoteRealtimeData.SetAnalogDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetAnalogDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string myOrganizationId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Balance.Service.ServiceReference_RemoteRealtimeData.ArrayOfString myTagName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Balance.Service.ServiceReference_RemoteRealtimeData.ArrayOfDecimal myTagValue;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string myKeyword;
        
        public SetAnalogDataRequestBody() {
        }
        
        public SetAnalogDataRequestBody(string myOrganizationId, Balance.Service.ServiceReference_RemoteRealtimeData.ArrayOfString myTagName, Balance.Service.ServiceReference_RemoteRealtimeData.ArrayOfDecimal myTagValue, string myKeyword) {
            this.myOrganizationId = myOrganizationId;
            this.myTagName = myTagName;
            this.myTagValue = myTagValue;
            this.myKeyword = myKeyword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetAnalogDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetAnalogDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public Balance.Service.ServiceReference_RemoteRealtimeData.SetAnalogDataResponseBody Body;
        
        public SetAnalogDataResponse() {
        }
        
        public SetAnalogDataResponse(Balance.Service.ServiceReference_RemoteRealtimeData.SetAnalogDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SetAnalogDataResponseBody {
        
        public SetAnalogDataResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetAnalogDataCompressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetAnalogDataCompress", Namespace="http://tempuri.org/", Order=0)]
        public Balance.Service.ServiceReference_RemoteRealtimeData.SetAnalogDataCompressRequestBody Body;
        
        public SetAnalogDataCompressRequest() {
        }
        
        public SetAnalogDataCompressRequest(Balance.Service.ServiceReference_RemoteRealtimeData.SetAnalogDataCompressRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetAnalogDataCompressRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string myOrganizationId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] myTagName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] myTagValue;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string myKeyword;
        
        public SetAnalogDataCompressRequestBody() {
        }
        
        public SetAnalogDataCompressRequestBody(string myOrganizationId, byte[] myTagName, byte[] myTagValue, string myKeyword) {
            this.myOrganizationId = myOrganizationId;
            this.myTagName = myTagName;
            this.myTagValue = myTagValue;
            this.myKeyword = myKeyword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetAnalogDataCompressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetAnalogDataCompressResponse", Namespace="http://tempuri.org/", Order=0)]
        public Balance.Service.ServiceReference_RemoteRealtimeData.SetAnalogDataCompressResponseBody Body;
        
        public SetAnalogDataCompressResponse() {
        }
        
        public SetAnalogDataCompressResponse(Balance.Service.ServiceReference_RemoteRealtimeData.SetAnalogDataCompressResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SetAnalogDataCompressResponseBody {
        
        public SetAnalogDataCompressResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetDigitalDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetDigitalData", Namespace="http://tempuri.org/", Order=0)]
        public Balance.Service.ServiceReference_RemoteRealtimeData.SetDigitalDataRequestBody Body;
        
        public SetDigitalDataRequest() {
        }
        
        public SetDigitalDataRequest(Balance.Service.ServiceReference_RemoteRealtimeData.SetDigitalDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetDigitalDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string myOrganizationId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Balance.Service.ServiceReference_RemoteRealtimeData.ArrayOfString myTagName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Balance.Service.ServiceReference_RemoteRealtimeData.ArrayOfBoolean myTagValue;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string myKeyword;
        
        public SetDigitalDataRequestBody() {
        }
        
        public SetDigitalDataRequestBody(string myOrganizationId, Balance.Service.ServiceReference_RemoteRealtimeData.ArrayOfString myTagName, Balance.Service.ServiceReference_RemoteRealtimeData.ArrayOfBoolean myTagValue, string myKeyword) {
            this.myOrganizationId = myOrganizationId;
            this.myTagName = myTagName;
            this.myTagValue = myTagValue;
            this.myKeyword = myKeyword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetDigitalDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetDigitalDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public Balance.Service.ServiceReference_RemoteRealtimeData.SetDigitalDataResponseBody Body;
        
        public SetDigitalDataResponse() {
        }
        
        public SetDigitalDataResponse(Balance.Service.ServiceReference_RemoteRealtimeData.SetDigitalDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SetDigitalDataResponseBody {
        
        public SetDigitalDataResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetDigitalDataCompressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetDigitalDataCompress", Namespace="http://tempuri.org/", Order=0)]
        public Balance.Service.ServiceReference_RemoteRealtimeData.SetDigitalDataCompressRequestBody Body;
        
        public SetDigitalDataCompressRequest() {
        }
        
        public SetDigitalDataCompressRequest(Balance.Service.ServiceReference_RemoteRealtimeData.SetDigitalDataCompressRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetDigitalDataCompressRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string myOrganizationId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] myTagName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] myTagValue;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string myKeyword;
        
        public SetDigitalDataCompressRequestBody() {
        }
        
        public SetDigitalDataCompressRequestBody(string myOrganizationId, byte[] myTagName, byte[] myTagValue, string myKeyword) {
            this.myOrganizationId = myOrganizationId;
            this.myTagName = myTagName;
            this.myTagValue = myTagValue;
            this.myKeyword = myKeyword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetDigitalDataCompressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetDigitalDataCompressResponse", Namespace="http://tempuri.org/", Order=0)]
        public Balance.Service.ServiceReference_RemoteRealtimeData.SetDigitalDataCompressResponseBody Body;
        
        public SetDigitalDataCompressResponse() {
        }
        
        public SetDigitalDataCompressResponse(Balance.Service.ServiceReference_RemoteRealtimeData.SetDigitalDataCompressResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SetDigitalDataCompressResponseBody {
        
        public SetDigitalDataCompressResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDigitalDataARequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDigitalDataA", Namespace="http://tempuri.org/", Order=0)]
        public Balance.Service.ServiceReference_RemoteRealtimeData.GetDigitalDataARequestBody Body;
        
        public GetDigitalDataARequest() {
        }
        
        public GetDigitalDataARequest(Balance.Service.ServiceReference_RemoteRealtimeData.GetDigitalDataARequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDigitalDataARequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string myOrganizationId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Balance.Service.ServiceReference_RemoteRealtimeData.ArrayOfString myTagName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string myKeyword;
        
        public GetDigitalDataARequestBody() {
        }
        
        public GetDigitalDataARequestBody(string myOrganizationId, Balance.Service.ServiceReference_RemoteRealtimeData.ArrayOfString myTagName, string myKeyword) {
            this.myOrganizationId = myOrganizationId;
            this.myTagName = myTagName;
            this.myKeyword = myKeyword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDigitalDataAResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDigitalDataAResponse", Namespace="http://tempuri.org/", Order=0)]
        public Balance.Service.ServiceReference_RemoteRealtimeData.GetDigitalDataAResponseBody Body;
        
        public GetDigitalDataAResponse() {
        }
        
        public GetDigitalDataAResponse(Balance.Service.ServiceReference_RemoteRealtimeData.GetDigitalDataAResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDigitalDataAResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Balance.Service.ServiceReference_RemoteRealtimeData.DigitalDataGroup_Serialization GetDigitalDataAResult;
        
        public GetDigitalDataAResponseBody() {
        }
        
        public GetDigitalDataAResponseBody(Balance.Service.ServiceReference_RemoteRealtimeData.DigitalDataGroup_Serialization GetDigitalDataAResult) {
            this.GetDigitalDataAResult = GetDigitalDataAResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAnalogDataARequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAnalogDataA", Namespace="http://tempuri.org/", Order=0)]
        public Balance.Service.ServiceReference_RemoteRealtimeData.GetAnalogDataARequestBody Body;
        
        public GetAnalogDataARequest() {
        }
        
        public GetAnalogDataARequest(Balance.Service.ServiceReference_RemoteRealtimeData.GetAnalogDataARequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAnalogDataARequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string myOrganizationId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Balance.Service.ServiceReference_RemoteRealtimeData.ArrayOfString myTagName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string myKeyword;
        
        public GetAnalogDataARequestBody() {
        }
        
        public GetAnalogDataARequestBody(string myOrganizationId, Balance.Service.ServiceReference_RemoteRealtimeData.ArrayOfString myTagName, string myKeyword) {
            this.myOrganizationId = myOrganizationId;
            this.myTagName = myTagName;
            this.myKeyword = myKeyword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAnalogDataAResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAnalogDataAResponse", Namespace="http://tempuri.org/", Order=0)]
        public Balance.Service.ServiceReference_RemoteRealtimeData.GetAnalogDataAResponseBody Body;
        
        public GetAnalogDataAResponse() {
        }
        
        public GetAnalogDataAResponse(Balance.Service.ServiceReference_RemoteRealtimeData.GetAnalogDataAResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAnalogDataAResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Balance.Service.ServiceReference_RemoteRealtimeData.AnalogDataGroup_Serialization GetAnalogDataAResult;
        
        public GetAnalogDataAResponseBody() {
        }
        
        public GetAnalogDataAResponseBody(Balance.Service.ServiceReference_RemoteRealtimeData.AnalogDataGroup_Serialization GetAnalogDataAResult) {
            this.GetAnalogDataAResult = GetAnalogDataAResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetObjectDataARequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetObjectDataA", Namespace="http://tempuri.org/", Order=0)]
        public Balance.Service.ServiceReference_RemoteRealtimeData.GetObjectDataARequestBody Body;
        
        public GetObjectDataARequest() {
        }
        
        public GetObjectDataARequest(Balance.Service.ServiceReference_RemoteRealtimeData.GetObjectDataARequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetObjectDataARequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string myOrganizationId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Balance.Service.ServiceReference_RemoteRealtimeData.ArrayOfString myTagName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string myKeyword;
        
        public GetObjectDataARequestBody() {
        }
        
        public GetObjectDataARequestBody(string myOrganizationId, Balance.Service.ServiceReference_RemoteRealtimeData.ArrayOfString myTagName, string myKeyword) {
            this.myOrganizationId = myOrganizationId;
            this.myTagName = myTagName;
            this.myKeyword = myKeyword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetObjectDataAResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetObjectDataAResponse", Namespace="http://tempuri.org/", Order=0)]
        public Balance.Service.ServiceReference_RemoteRealtimeData.GetObjectDataAResponseBody Body;
        
        public GetObjectDataAResponse() {
        }
        
        public GetObjectDataAResponse(Balance.Service.ServiceReference_RemoteRealtimeData.GetObjectDataAResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetObjectDataAResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Balance.Service.ServiceReference_RemoteRealtimeData.ObjectDataGroup_Serialization GetObjectDataAResult;
        
        public GetObjectDataAResponseBody() {
        }
        
        public GetObjectDataAResponseBody(Balance.Service.ServiceReference_RemoteRealtimeData.ObjectDataGroup_Serialization GetObjectDataAResult) {
            this.GetObjectDataAResult = GetObjectDataAResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDigitalDataSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDigitalDataS", Namespace="http://tempuri.org/", Order=0)]
        public Balance.Service.ServiceReference_RemoteRealtimeData.GetDigitalDataSRequestBody Body;
        
        public GetDigitalDataSRequest() {
        }
        
        public GetDigitalDataSRequest(Balance.Service.ServiceReference_RemoteRealtimeData.GetDigitalDataSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDigitalDataSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string myOrganizationId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string myTagName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string myKeyword;
        
        public GetDigitalDataSRequestBody() {
        }
        
        public GetDigitalDataSRequestBody(string myOrganizationId, string myTagName, string myKeyword) {
            this.myOrganizationId = myOrganizationId;
            this.myTagName = myTagName;
            this.myKeyword = myKeyword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDigitalDataSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDigitalDataSResponse", Namespace="http://tempuri.org/", Order=0)]
        public Balance.Service.ServiceReference_RemoteRealtimeData.GetDigitalDataSResponseBody Body;
        
        public GetDigitalDataSResponse() {
        }
        
        public GetDigitalDataSResponse(Balance.Service.ServiceReference_RemoteRealtimeData.GetDigitalDataSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDigitalDataSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDigitalDataSResult;
        
        public GetDigitalDataSResponseBody() {
        }
        
        public GetDigitalDataSResponseBody(string GetDigitalDataSResult) {
            this.GetDigitalDataSResult = GetDigitalDataSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAnalogDataSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAnalogDataS", Namespace="http://tempuri.org/", Order=0)]
        public Balance.Service.ServiceReference_RemoteRealtimeData.GetAnalogDataSRequestBody Body;
        
        public GetAnalogDataSRequest() {
        }
        
        public GetAnalogDataSRequest(Balance.Service.ServiceReference_RemoteRealtimeData.GetAnalogDataSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAnalogDataSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string myOrganizationId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string myTagName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string myKeyword;
        
        public GetAnalogDataSRequestBody() {
        }
        
        public GetAnalogDataSRequestBody(string myOrganizationId, string myTagName, string myKeyword) {
            this.myOrganizationId = myOrganizationId;
            this.myTagName = myTagName;
            this.myKeyword = myKeyword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAnalogDataSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAnalogDataSResponse", Namespace="http://tempuri.org/", Order=0)]
        public Balance.Service.ServiceReference_RemoteRealtimeData.GetAnalogDataSResponseBody Body;
        
        public GetAnalogDataSResponse() {
        }
        
        public GetAnalogDataSResponse(Balance.Service.ServiceReference_RemoteRealtimeData.GetAnalogDataSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAnalogDataSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAnalogDataSResult;
        
        public GetAnalogDataSResponseBody() {
        }
        
        public GetAnalogDataSResponseBody(string GetAnalogDataSResult) {
            this.GetAnalogDataSResult = GetAnalogDataSResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RealTimeDataSoapChannel : Balance.Service.ServiceReference_RemoteRealtimeData.RealTimeDataSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RealTimeDataSoapClient : System.ServiceModel.ClientBase<Balance.Service.ServiceReference_RemoteRealtimeData.RealTimeDataSoap>, Balance.Service.ServiceReference_RemoteRealtimeData.RealTimeDataSoap {
        
        public RealTimeDataSoapClient() {
        }
        
        public RealTimeDataSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RealTimeDataSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RealTimeDataSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RealTimeDataSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Balance.Service.ServiceReference_RemoteRealtimeData.HelloWorldResponse Balance.Service.ServiceReference_RemoteRealtimeData.RealTimeDataSoap.HelloWorld(Balance.Service.ServiceReference_RemoteRealtimeData.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Balance.Service.ServiceReference_RemoteRealtimeData.HelloWorldRequest inValue = new Balance.Service.ServiceReference_RemoteRealtimeData.HelloWorldRequest();
            inValue.Body = new Balance.Service.ServiceReference_RemoteRealtimeData.HelloWorldRequestBody();
            Balance.Service.ServiceReference_RemoteRealtimeData.HelloWorldResponse retVal = ((Balance.Service.ServiceReference_RemoteRealtimeData.RealTimeDataSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Balance.Service.ServiceReference_RemoteRealtimeData.SetAnalogDataResponse Balance.Service.ServiceReference_RemoteRealtimeData.RealTimeDataSoap.SetAnalogData(Balance.Service.ServiceReference_RemoteRealtimeData.SetAnalogDataRequest request) {
            return base.Channel.SetAnalogData(request);
        }
        
        public void SetAnalogData(string myOrganizationId, Balance.Service.ServiceReference_RemoteRealtimeData.ArrayOfString myTagName, Balance.Service.ServiceReference_RemoteRealtimeData.ArrayOfDecimal myTagValue, string myKeyword) {
            Balance.Service.ServiceReference_RemoteRealtimeData.SetAnalogDataRequest inValue = new Balance.Service.ServiceReference_RemoteRealtimeData.SetAnalogDataRequest();
            inValue.Body = new Balance.Service.ServiceReference_RemoteRealtimeData.SetAnalogDataRequestBody();
            inValue.Body.myOrganizationId = myOrganizationId;
            inValue.Body.myTagName = myTagName;
            inValue.Body.myTagValue = myTagValue;
            inValue.Body.myKeyword = myKeyword;
            Balance.Service.ServiceReference_RemoteRealtimeData.SetAnalogDataResponse retVal = ((Balance.Service.ServiceReference_RemoteRealtimeData.RealTimeDataSoap)(this)).SetAnalogData(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Balance.Service.ServiceReference_RemoteRealtimeData.SetAnalogDataCompressResponse Balance.Service.ServiceReference_RemoteRealtimeData.RealTimeDataSoap.SetAnalogDataCompress(Balance.Service.ServiceReference_RemoteRealtimeData.SetAnalogDataCompressRequest request) {
            return base.Channel.SetAnalogDataCompress(request);
        }
        
        public void SetAnalogDataCompress(string myOrganizationId, byte[] myTagName, byte[] myTagValue, string myKeyword) {
            Balance.Service.ServiceReference_RemoteRealtimeData.SetAnalogDataCompressRequest inValue = new Balance.Service.ServiceReference_RemoteRealtimeData.SetAnalogDataCompressRequest();
            inValue.Body = new Balance.Service.ServiceReference_RemoteRealtimeData.SetAnalogDataCompressRequestBody();
            inValue.Body.myOrganizationId = myOrganizationId;
            inValue.Body.myTagName = myTagName;
            inValue.Body.myTagValue = myTagValue;
            inValue.Body.myKeyword = myKeyword;
            Balance.Service.ServiceReference_RemoteRealtimeData.SetAnalogDataCompressResponse retVal = ((Balance.Service.ServiceReference_RemoteRealtimeData.RealTimeDataSoap)(this)).SetAnalogDataCompress(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Balance.Service.ServiceReference_RemoteRealtimeData.SetDigitalDataResponse Balance.Service.ServiceReference_RemoteRealtimeData.RealTimeDataSoap.SetDigitalData(Balance.Service.ServiceReference_RemoteRealtimeData.SetDigitalDataRequest request) {
            return base.Channel.SetDigitalData(request);
        }
        
        public void SetDigitalData(string myOrganizationId, Balance.Service.ServiceReference_RemoteRealtimeData.ArrayOfString myTagName, Balance.Service.ServiceReference_RemoteRealtimeData.ArrayOfBoolean myTagValue, string myKeyword) {
            Balance.Service.ServiceReference_RemoteRealtimeData.SetDigitalDataRequest inValue = new Balance.Service.ServiceReference_RemoteRealtimeData.SetDigitalDataRequest();
            inValue.Body = new Balance.Service.ServiceReference_RemoteRealtimeData.SetDigitalDataRequestBody();
            inValue.Body.myOrganizationId = myOrganizationId;
            inValue.Body.myTagName = myTagName;
            inValue.Body.myTagValue = myTagValue;
            inValue.Body.myKeyword = myKeyword;
            Balance.Service.ServiceReference_RemoteRealtimeData.SetDigitalDataResponse retVal = ((Balance.Service.ServiceReference_RemoteRealtimeData.RealTimeDataSoap)(this)).SetDigitalData(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Balance.Service.ServiceReference_RemoteRealtimeData.SetDigitalDataCompressResponse Balance.Service.ServiceReference_RemoteRealtimeData.RealTimeDataSoap.SetDigitalDataCompress(Balance.Service.ServiceReference_RemoteRealtimeData.SetDigitalDataCompressRequest request) {
            return base.Channel.SetDigitalDataCompress(request);
        }
        
        public void SetDigitalDataCompress(string myOrganizationId, byte[] myTagName, byte[] myTagValue, string myKeyword) {
            Balance.Service.ServiceReference_RemoteRealtimeData.SetDigitalDataCompressRequest inValue = new Balance.Service.ServiceReference_RemoteRealtimeData.SetDigitalDataCompressRequest();
            inValue.Body = new Balance.Service.ServiceReference_RemoteRealtimeData.SetDigitalDataCompressRequestBody();
            inValue.Body.myOrganizationId = myOrganizationId;
            inValue.Body.myTagName = myTagName;
            inValue.Body.myTagValue = myTagValue;
            inValue.Body.myKeyword = myKeyword;
            Balance.Service.ServiceReference_RemoteRealtimeData.SetDigitalDataCompressResponse retVal = ((Balance.Service.ServiceReference_RemoteRealtimeData.RealTimeDataSoap)(this)).SetDigitalDataCompress(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Balance.Service.ServiceReference_RemoteRealtimeData.GetDigitalDataAResponse Balance.Service.ServiceReference_RemoteRealtimeData.RealTimeDataSoap.GetDigitalDataA(Balance.Service.ServiceReference_RemoteRealtimeData.GetDigitalDataARequest request) {
            return base.Channel.GetDigitalDataA(request);
        }
        
        public Balance.Service.ServiceReference_RemoteRealtimeData.DigitalDataGroup_Serialization GetDigitalDataA(string myOrganizationId, Balance.Service.ServiceReference_RemoteRealtimeData.ArrayOfString myTagName, string myKeyword) {
            Balance.Service.ServiceReference_RemoteRealtimeData.GetDigitalDataARequest inValue = new Balance.Service.ServiceReference_RemoteRealtimeData.GetDigitalDataARequest();
            inValue.Body = new Balance.Service.ServiceReference_RemoteRealtimeData.GetDigitalDataARequestBody();
            inValue.Body.myOrganizationId = myOrganizationId;
            inValue.Body.myTagName = myTagName;
            inValue.Body.myKeyword = myKeyword;
            Balance.Service.ServiceReference_RemoteRealtimeData.GetDigitalDataAResponse retVal = ((Balance.Service.ServiceReference_RemoteRealtimeData.RealTimeDataSoap)(this)).GetDigitalDataA(inValue);
            return retVal.Body.GetDigitalDataAResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Balance.Service.ServiceReference_RemoteRealtimeData.GetAnalogDataAResponse Balance.Service.ServiceReference_RemoteRealtimeData.RealTimeDataSoap.GetAnalogDataA(Balance.Service.ServiceReference_RemoteRealtimeData.GetAnalogDataARequest request) {
            return base.Channel.GetAnalogDataA(request);
        }
        
        public Balance.Service.ServiceReference_RemoteRealtimeData.AnalogDataGroup_Serialization GetAnalogDataA(string myOrganizationId, Balance.Service.ServiceReference_RemoteRealtimeData.ArrayOfString myTagName, string myKeyword) {
            Balance.Service.ServiceReference_RemoteRealtimeData.GetAnalogDataARequest inValue = new Balance.Service.ServiceReference_RemoteRealtimeData.GetAnalogDataARequest();
            inValue.Body = new Balance.Service.ServiceReference_RemoteRealtimeData.GetAnalogDataARequestBody();
            inValue.Body.myOrganizationId = myOrganizationId;
            inValue.Body.myTagName = myTagName;
            inValue.Body.myKeyword = myKeyword;
            Balance.Service.ServiceReference_RemoteRealtimeData.GetAnalogDataAResponse retVal = ((Balance.Service.ServiceReference_RemoteRealtimeData.RealTimeDataSoap)(this)).GetAnalogDataA(inValue);
            return retVal.Body.GetAnalogDataAResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Balance.Service.ServiceReference_RemoteRealtimeData.GetObjectDataAResponse Balance.Service.ServiceReference_RemoteRealtimeData.RealTimeDataSoap.GetObjectDataA(Balance.Service.ServiceReference_RemoteRealtimeData.GetObjectDataARequest request) {
            return base.Channel.GetObjectDataA(request);
        }
        
        public Balance.Service.ServiceReference_RemoteRealtimeData.ObjectDataGroup_Serialization GetObjectDataA(string myOrganizationId, Balance.Service.ServiceReference_RemoteRealtimeData.ArrayOfString myTagName, string myKeyword) {
            Balance.Service.ServiceReference_RemoteRealtimeData.GetObjectDataARequest inValue = new Balance.Service.ServiceReference_RemoteRealtimeData.GetObjectDataARequest();
            inValue.Body = new Balance.Service.ServiceReference_RemoteRealtimeData.GetObjectDataARequestBody();
            inValue.Body.myOrganizationId = myOrganizationId;
            inValue.Body.myTagName = myTagName;
            inValue.Body.myKeyword = myKeyword;
            Balance.Service.ServiceReference_RemoteRealtimeData.GetObjectDataAResponse retVal = ((Balance.Service.ServiceReference_RemoteRealtimeData.RealTimeDataSoap)(this)).GetObjectDataA(inValue);
            return retVal.Body.GetObjectDataAResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Balance.Service.ServiceReference_RemoteRealtimeData.GetDigitalDataSResponse Balance.Service.ServiceReference_RemoteRealtimeData.RealTimeDataSoap.GetDigitalDataS(Balance.Service.ServiceReference_RemoteRealtimeData.GetDigitalDataSRequest request) {
            return base.Channel.GetDigitalDataS(request);
        }
        
        public string GetDigitalDataS(string myOrganizationId, string myTagName, string myKeyword) {
            Balance.Service.ServiceReference_RemoteRealtimeData.GetDigitalDataSRequest inValue = new Balance.Service.ServiceReference_RemoteRealtimeData.GetDigitalDataSRequest();
            inValue.Body = new Balance.Service.ServiceReference_RemoteRealtimeData.GetDigitalDataSRequestBody();
            inValue.Body.myOrganizationId = myOrganizationId;
            inValue.Body.myTagName = myTagName;
            inValue.Body.myKeyword = myKeyword;
            Balance.Service.ServiceReference_RemoteRealtimeData.GetDigitalDataSResponse retVal = ((Balance.Service.ServiceReference_RemoteRealtimeData.RealTimeDataSoap)(this)).GetDigitalDataS(inValue);
            return retVal.Body.GetDigitalDataSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Balance.Service.ServiceReference_RemoteRealtimeData.GetAnalogDataSResponse Balance.Service.ServiceReference_RemoteRealtimeData.RealTimeDataSoap.GetAnalogDataS(Balance.Service.ServiceReference_RemoteRealtimeData.GetAnalogDataSRequest request) {
            return base.Channel.GetAnalogDataS(request);
        }
        
        public string GetAnalogDataS(string myOrganizationId, string myTagName, string myKeyword) {
            Balance.Service.ServiceReference_RemoteRealtimeData.GetAnalogDataSRequest inValue = new Balance.Service.ServiceReference_RemoteRealtimeData.GetAnalogDataSRequest();
            inValue.Body = new Balance.Service.ServiceReference_RemoteRealtimeData.GetAnalogDataSRequestBody();
            inValue.Body.myOrganizationId = myOrganizationId;
            inValue.Body.myTagName = myTagName;
            inValue.Body.myKeyword = myKeyword;
            Balance.Service.ServiceReference_RemoteRealtimeData.GetAnalogDataSResponse retVal = ((Balance.Service.ServiceReference_RemoteRealtimeData.RealTimeDataSoap)(this)).GetAnalogDataS(inValue);
            return retVal.Body.GetAnalogDataSResult;
        }
    }
}
