//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Balance.Service.ServiceReference_RemoteRealtimeData {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfDecimal", Namespace="http://tempuri.org/", ItemName="decimal")]
    [System.SerializableAttribute()]
    public class ArrayOfDecimal : System.Collections.Generic.List<decimal> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfBoolean", Namespace="http://tempuri.org/", ItemName="boolean")]
    [System.SerializableAttribute()]
    public class ArrayOfBoolean : System.Collections.Generic.List<bool> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference_RemoteRealtimeData.RealTimeDataSoap")]
    public interface RealTimeDataSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Balance.Service.ServiceReference_RemoteRealtimeData.HelloWorldResponse HelloWorld(Balance.Service.ServiceReference_RemoteRealtimeData.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 myOrganizationId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetAnalogData", ReplyAction="*")]
        Balance.Service.ServiceReference_RemoteRealtimeData.SetAnalogDataResponse SetAnalogData(Balance.Service.ServiceReference_RemoteRealtimeData.SetAnalogDataRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 myOrganizationId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetDigitalData", ReplyAction="*")]
        Balance.Service.ServiceReference_RemoteRealtimeData.SetDigitalDataResponse SetDigitalData(Balance.Service.ServiceReference_RemoteRealtimeData.SetDigitalDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Balance.Service.ServiceReference_RemoteRealtimeData.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Balance.Service.ServiceReference_RemoteRealtimeData.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Balance.Service.ServiceReference_RemoteRealtimeData.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Balance.Service.ServiceReference_RemoteRealtimeData.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetAnalogDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetAnalogData", Namespace="http://tempuri.org/", Order=0)]
        public Balance.Service.ServiceReference_RemoteRealtimeData.SetAnalogDataRequestBody Body;
        
        public SetAnalogDataRequest() {
        }
        
        public SetAnalogDataRequest(Balance.Service.ServiceReference_RemoteRealtimeData.SetAnalogDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetAnalogDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string myOrganizationId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Balance.Service.ServiceReference_RemoteRealtimeData.ArrayOfString myTagName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Balance.Service.ServiceReference_RemoteRealtimeData.ArrayOfDecimal myTagValue;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string myKeyword;
        
        public SetAnalogDataRequestBody() {
        }
        
        public SetAnalogDataRequestBody(string myOrganizationId, Balance.Service.ServiceReference_RemoteRealtimeData.ArrayOfString myTagName, Balance.Service.ServiceReference_RemoteRealtimeData.ArrayOfDecimal myTagValue, string myKeyword) {
            this.myOrganizationId = myOrganizationId;
            this.myTagName = myTagName;
            this.myTagValue = myTagValue;
            this.myKeyword = myKeyword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetAnalogDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetAnalogDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public Balance.Service.ServiceReference_RemoteRealtimeData.SetAnalogDataResponseBody Body;
        
        public SetAnalogDataResponse() {
        }
        
        public SetAnalogDataResponse(Balance.Service.ServiceReference_RemoteRealtimeData.SetAnalogDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SetAnalogDataResponseBody {
        
        public SetAnalogDataResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetDigitalDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetDigitalData", Namespace="http://tempuri.org/", Order=0)]
        public Balance.Service.ServiceReference_RemoteRealtimeData.SetDigitalDataRequestBody Body;
        
        public SetDigitalDataRequest() {
        }
        
        public SetDigitalDataRequest(Balance.Service.ServiceReference_RemoteRealtimeData.SetDigitalDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetDigitalDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string myOrganizationId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Balance.Service.ServiceReference_RemoteRealtimeData.ArrayOfString myTagName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Balance.Service.ServiceReference_RemoteRealtimeData.ArrayOfBoolean myTagValue;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string myKeyword;
        
        public SetDigitalDataRequestBody() {
        }
        
        public SetDigitalDataRequestBody(string myOrganizationId, Balance.Service.ServiceReference_RemoteRealtimeData.ArrayOfString myTagName, Balance.Service.ServiceReference_RemoteRealtimeData.ArrayOfBoolean myTagValue, string myKeyword) {
            this.myOrganizationId = myOrganizationId;
            this.myTagName = myTagName;
            this.myTagValue = myTagValue;
            this.myKeyword = myKeyword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetDigitalDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetDigitalDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public Balance.Service.ServiceReference_RemoteRealtimeData.SetDigitalDataResponseBody Body;
        
        public SetDigitalDataResponse() {
        }
        
        public SetDigitalDataResponse(Balance.Service.ServiceReference_RemoteRealtimeData.SetDigitalDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SetDigitalDataResponseBody {
        
        public SetDigitalDataResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RealTimeDataSoapChannel : Balance.Service.ServiceReference_RemoteRealtimeData.RealTimeDataSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RealTimeDataSoapClient : System.ServiceModel.ClientBase<Balance.Service.ServiceReference_RemoteRealtimeData.RealTimeDataSoap>, Balance.Service.ServiceReference_RemoteRealtimeData.RealTimeDataSoap {
        
        public RealTimeDataSoapClient() {
        }
        
        public RealTimeDataSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RealTimeDataSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RealTimeDataSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RealTimeDataSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Balance.Service.ServiceReference_RemoteRealtimeData.HelloWorldResponse Balance.Service.ServiceReference_RemoteRealtimeData.RealTimeDataSoap.HelloWorld(Balance.Service.ServiceReference_RemoteRealtimeData.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Balance.Service.ServiceReference_RemoteRealtimeData.HelloWorldRequest inValue = new Balance.Service.ServiceReference_RemoteRealtimeData.HelloWorldRequest();
            inValue.Body = new Balance.Service.ServiceReference_RemoteRealtimeData.HelloWorldRequestBody();
            Balance.Service.ServiceReference_RemoteRealtimeData.HelloWorldResponse retVal = ((Balance.Service.ServiceReference_RemoteRealtimeData.RealTimeDataSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Balance.Service.ServiceReference_RemoteRealtimeData.SetAnalogDataResponse Balance.Service.ServiceReference_RemoteRealtimeData.RealTimeDataSoap.SetAnalogData(Balance.Service.ServiceReference_RemoteRealtimeData.SetAnalogDataRequest request) {
            return base.Channel.SetAnalogData(request);
        }
        
        public void SetAnalogData(string myOrganizationId, Balance.Service.ServiceReference_RemoteRealtimeData.ArrayOfString myTagName, Balance.Service.ServiceReference_RemoteRealtimeData.ArrayOfDecimal myTagValue, string myKeyword) {
            Balance.Service.ServiceReference_RemoteRealtimeData.SetAnalogDataRequest inValue = new Balance.Service.ServiceReference_RemoteRealtimeData.SetAnalogDataRequest();
            inValue.Body = new Balance.Service.ServiceReference_RemoteRealtimeData.SetAnalogDataRequestBody();
            inValue.Body.myOrganizationId = myOrganizationId;
            inValue.Body.myTagName = myTagName;
            inValue.Body.myTagValue = myTagValue;
            inValue.Body.myKeyword = myKeyword;
            Balance.Service.ServiceReference_RemoteRealtimeData.SetAnalogDataResponse retVal = ((Balance.Service.ServiceReference_RemoteRealtimeData.RealTimeDataSoap)(this)).SetAnalogData(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Balance.Service.ServiceReference_RemoteRealtimeData.SetDigitalDataResponse Balance.Service.ServiceReference_RemoteRealtimeData.RealTimeDataSoap.SetDigitalData(Balance.Service.ServiceReference_RemoteRealtimeData.SetDigitalDataRequest request) {
            return base.Channel.SetDigitalData(request);
        }
        
        public void SetDigitalData(string myOrganizationId, Balance.Service.ServiceReference_RemoteRealtimeData.ArrayOfString myTagName, Balance.Service.ServiceReference_RemoteRealtimeData.ArrayOfBoolean myTagValue, string myKeyword) {
            Balance.Service.ServiceReference_RemoteRealtimeData.SetDigitalDataRequest inValue = new Balance.Service.ServiceReference_RemoteRealtimeData.SetDigitalDataRequest();
            inValue.Body = new Balance.Service.ServiceReference_RemoteRealtimeData.SetDigitalDataRequestBody();
            inValue.Body.myOrganizationId = myOrganizationId;
            inValue.Body.myTagName = myTagName;
            inValue.Body.myTagValue = myTagValue;
            inValue.Body.myKeyword = myKeyword;
            Balance.Service.ServiceReference_RemoteRealtimeData.SetDigitalDataResponse retVal = ((Balance.Service.ServiceReference_RemoteRealtimeData.RealTimeDataSoap)(this)).SetDigitalData(inValue);
        }
    }
}
