//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Balance.Service.ServiceReference_LocalSystemStatus {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference_LocalSystemStatus.NetworkMonitorSoap")]
    public interface NetworkMonitorSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Balance.Service.ServiceReference_LocalSystemStatus.HelloWorldResponse HelloWorld(Balance.Service.ServiceReference_LocalSystemStatus.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 myOrganizationId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetNetworkStatus", ReplyAction="*")]
        Balance.Service.ServiceReference_LocalSystemStatus.SetNetworkStatusResponse SetNetworkStatus(Balance.Service.ServiceReference_LocalSystemStatus.SetNetworkStatusRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetNetworkStatusResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNetworkStatus", ReplyAction="*")]
        Balance.Service.ServiceReference_LocalSystemStatus.GetNetworkStatusResponse GetNetworkStatus(Balance.Service.ServiceReference_LocalSystemStatus.GetNetworkStatusRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetNetworkStructureResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNetworkStructure", ReplyAction="*")]
        Balance.Service.ServiceReference_LocalSystemStatus.GetNetworkStructureResponse GetNetworkStructure(Balance.Service.ServiceReference_LocalSystemStatus.GetNetworkStructureRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Balance.Service.ServiceReference_LocalSystemStatus.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Balance.Service.ServiceReference_LocalSystemStatus.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Balance.Service.ServiceReference_LocalSystemStatus.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Balance.Service.ServiceReference_LocalSystemStatus.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetNetworkStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetNetworkStatus", Namespace="http://tempuri.org/", Order=0)]
        public Balance.Service.ServiceReference_LocalSystemStatus.SetNetworkStatusRequestBody Body;
        
        public SetNetworkStatusRequest() {
        }
        
        public SetNetworkStatusRequest(Balance.Service.ServiceReference_LocalSystemStatus.SetNetworkStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetNetworkStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string myOrganizationId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string myTimeStamp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] myStatusBuffer;
        
        public SetNetworkStatusRequestBody() {
        }
        
        public SetNetworkStatusRequestBody(string myOrganizationId, string myTimeStamp, byte[] myStatusBuffer) {
            this.myOrganizationId = myOrganizationId;
            this.myTimeStamp = myTimeStamp;
            this.myStatusBuffer = myStatusBuffer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetNetworkStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetNetworkStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public Balance.Service.ServiceReference_LocalSystemStatus.SetNetworkStatusResponseBody Body;
        
        public SetNetworkStatusResponse() {
        }
        
        public SetNetworkStatusResponse(Balance.Service.ServiceReference_LocalSystemStatus.SetNetworkStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SetNetworkStatusResponseBody {
        
        public SetNetworkStatusResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNetworkStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNetworkStatus", Namespace="http://tempuri.org/", Order=0)]
        public Balance.Service.ServiceReference_LocalSystemStatus.GetNetworkStatusRequestBody Body;
        
        public GetNetworkStatusRequest() {
        }
        
        public GetNetworkStatusRequest(Balance.Service.ServiceReference_LocalSystemStatus.GetNetworkStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetNetworkStatusRequestBody {
        
        public GetNetworkStatusRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNetworkStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNetworkStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public Balance.Service.ServiceReference_LocalSystemStatus.GetNetworkStatusResponseBody Body;
        
        public GetNetworkStatusResponse() {
        }
        
        public GetNetworkStatusResponse(Balance.Service.ServiceReference_LocalSystemStatus.GetNetworkStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNetworkStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetNetworkStatusResult;
        
        public GetNetworkStatusResponseBody() {
        }
        
        public GetNetworkStatusResponseBody(string GetNetworkStatusResult) {
            this.GetNetworkStatusResult = GetNetworkStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNetworkStructureRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNetworkStructure", Namespace="http://tempuri.org/", Order=0)]
        public Balance.Service.ServiceReference_LocalSystemStatus.GetNetworkStructureRequestBody Body;
        
        public GetNetworkStructureRequest() {
        }
        
        public GetNetworkStructureRequest(Balance.Service.ServiceReference_LocalSystemStatus.GetNetworkStructureRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetNetworkStructureRequestBody {
        
        public GetNetworkStructureRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNetworkStructureResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNetworkStructureResponse", Namespace="http://tempuri.org/", Order=0)]
        public Balance.Service.ServiceReference_LocalSystemStatus.GetNetworkStructureResponseBody Body;
        
        public GetNetworkStructureResponse() {
        }
        
        public GetNetworkStructureResponse(Balance.Service.ServiceReference_LocalSystemStatus.GetNetworkStructureResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNetworkStructureResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetNetworkStructureResult;
        
        public GetNetworkStructureResponseBody() {
        }
        
        public GetNetworkStructureResponseBody(string GetNetworkStructureResult) {
            this.GetNetworkStructureResult = GetNetworkStructureResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NetworkMonitorSoapChannel : Balance.Service.ServiceReference_LocalSystemStatus.NetworkMonitorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NetworkMonitorSoapClient : System.ServiceModel.ClientBase<Balance.Service.ServiceReference_LocalSystemStatus.NetworkMonitorSoap>, Balance.Service.ServiceReference_LocalSystemStatus.NetworkMonitorSoap {
        
        public NetworkMonitorSoapClient() {
        }
        
        public NetworkMonitorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NetworkMonitorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NetworkMonitorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NetworkMonitorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Balance.Service.ServiceReference_LocalSystemStatus.HelloWorldResponse Balance.Service.ServiceReference_LocalSystemStatus.NetworkMonitorSoap.HelloWorld(Balance.Service.ServiceReference_LocalSystemStatus.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Balance.Service.ServiceReference_LocalSystemStatus.HelloWorldRequest inValue = new Balance.Service.ServiceReference_LocalSystemStatus.HelloWorldRequest();
            inValue.Body = new Balance.Service.ServiceReference_LocalSystemStatus.HelloWorldRequestBody();
            Balance.Service.ServiceReference_LocalSystemStatus.HelloWorldResponse retVal = ((Balance.Service.ServiceReference_LocalSystemStatus.NetworkMonitorSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Balance.Service.ServiceReference_LocalSystemStatus.SetNetworkStatusResponse Balance.Service.ServiceReference_LocalSystemStatus.NetworkMonitorSoap.SetNetworkStatus(Balance.Service.ServiceReference_LocalSystemStatus.SetNetworkStatusRequest request) {
            return base.Channel.SetNetworkStatus(request);
        }
        
        public void SetNetworkStatus(string myOrganizationId, string myTimeStamp, byte[] myStatusBuffer) {
            Balance.Service.ServiceReference_LocalSystemStatus.SetNetworkStatusRequest inValue = new Balance.Service.ServiceReference_LocalSystemStatus.SetNetworkStatusRequest();
            inValue.Body = new Balance.Service.ServiceReference_LocalSystemStatus.SetNetworkStatusRequestBody();
            inValue.Body.myOrganizationId = myOrganizationId;
            inValue.Body.myTimeStamp = myTimeStamp;
            inValue.Body.myStatusBuffer = myStatusBuffer;
            Balance.Service.ServiceReference_LocalSystemStatus.SetNetworkStatusResponse retVal = ((Balance.Service.ServiceReference_LocalSystemStatus.NetworkMonitorSoap)(this)).SetNetworkStatus(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Balance.Service.ServiceReference_LocalSystemStatus.GetNetworkStatusResponse Balance.Service.ServiceReference_LocalSystemStatus.NetworkMonitorSoap.GetNetworkStatus(Balance.Service.ServiceReference_LocalSystemStatus.GetNetworkStatusRequest request) {
            return base.Channel.GetNetworkStatus(request);
        }
        
        public string GetNetworkStatus() {
            Balance.Service.ServiceReference_LocalSystemStatus.GetNetworkStatusRequest inValue = new Balance.Service.ServiceReference_LocalSystemStatus.GetNetworkStatusRequest();
            inValue.Body = new Balance.Service.ServiceReference_LocalSystemStatus.GetNetworkStatusRequestBody();
            Balance.Service.ServiceReference_LocalSystemStatus.GetNetworkStatusResponse retVal = ((Balance.Service.ServiceReference_LocalSystemStatus.NetworkMonitorSoap)(this)).GetNetworkStatus(inValue);
            return retVal.Body.GetNetworkStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Balance.Service.ServiceReference_LocalSystemStatus.GetNetworkStructureResponse Balance.Service.ServiceReference_LocalSystemStatus.NetworkMonitorSoap.GetNetworkStructure(Balance.Service.ServiceReference_LocalSystemStatus.GetNetworkStructureRequest request) {
            return base.Channel.GetNetworkStructure(request);
        }
        
        public string GetNetworkStructure() {
            Balance.Service.ServiceReference_LocalSystemStatus.GetNetworkStructureRequest inValue = new Balance.Service.ServiceReference_LocalSystemStatus.GetNetworkStructureRequest();
            inValue.Body = new Balance.Service.ServiceReference_LocalSystemStatus.GetNetworkStructureRequestBody();
            Balance.Service.ServiceReference_LocalSystemStatus.GetNetworkStructureResponse retVal = ((Balance.Service.ServiceReference_LocalSystemStatus.NetworkMonitorSoap)(this)).GetNetworkStructure(inValue);
            return retVal.Body.GetNetworkStructureResult;
        }
    }
}
